import type { ThemePalette, HelixExporterOptions } from '../types.js';

// ── TOML Serialization ─────────────────────────────────────────────────────────

interface HelixStyle {
  fg?: string;
  bg?: string;
  modifiers?: string[];
  underline?: { color?: string; style?: string };
}

function toml(key: string, style: HelixStyle): string {
  const parts: string[] = [];
  if (style.fg) parts.push(`fg = "${style.fg}"`);
  if (style.bg) parts.push(`bg = "${style.bg}"`);
  if (style.modifiers?.length) {
    parts.push(`modifiers = [${style.modifiers.map((m) => `"${m}"`).join(', ')}]`);
  }
  if (style.underline) {
    const ul: string[] = [];
    if (style.underline.color) ul.push(`color = "${style.underline.color}"`);
    if (style.underline.style) ul.push(`style = "${style.underline.style}"`);
    parts.push(`underline = { ${ul.join(', ')} }`);
  }
  return `"${key}" = { ${parts.join(', ')} }`;
}

// ── Main Exporter ──────────────────────────────────────────────────────────────

/**
 * Export a ThemePalette to Helix editor TOML theme format.
 *
 * Produces a complete `.toml` theme file string containing:
 * - UI scopes (ui.background, ui.cursor, ui.selection, ui.text, etc.)
 * - Diagnostic styles (undercurl with per-severity colors)
 * - Diff markers
 * - Markup scopes (heading, bold, italic, link)
 * - Syntax scopes (comment, keyword, function, variable, type, etc.)
 *
 * Helix supports #RRGGBBAA hex colors, so semi-transparent overlay colors
 * (selectionBg, lineHighlight, findMatch) are used directly with their alpha.
 *
 * @param palette - Resolved ThemePalette from extract() using createHelixSpec()
 * @param options - Optional name, author
 * @returns TOML string ready to save as a `.toml` Helix theme file
 */
export function exportHelix(palette: ThemePalette, options?: HelixExporterOptions): string {
  const name = options?.name ?? palette.spec;

  // Helix supports #RRGGBBAA — keep alpha intact
  const h = (role: string) => palette.hex(role) || '#000000';

  const lines: string[] = [];
  const ln = (...args: string[]) => lines.push(...args);

  // ── Header ─────────────────────────────────────────────────────────────────

  ln(
    `# ${name} — Sacred Geometry color theme for Helix`,
    `# Generated by @rlabs-inc/theme-generator`,
    ``,
  );

  // ── UI Scopes ──────────────────────────────────────────────────────────────

  ln('# ── UI ──────────────────────────────────────────────────────────────────────');
  ln(toml('ui.background',             { bg: h('bg1') }));
  ln(toml('ui.background.separator',   { fg: h('border') }));
  ln(toml('ui.text',                   { fg: h('fg1') }));
  ln(toml('ui.text.focus',             { fg: h('fg1') }));
  ln(toml('ui.text.inactive',          { fg: h('comment') }));
  ln(toml('ui.text.info',              { fg: h('info') }));

  // Cursor
  ln(toml('ui.cursor',                 { fg: h('cursorText'), bg: h('cursor') }));
  ln(toml('ui.cursor.primary',         { fg: h('cursorText'), bg: h('cursor') }));
  ln(toml('ui.cursor.insert',          { fg: h('cursorText'), bg: h('ac2') }));
  ln(toml('ui.cursor.select',          { fg: h('cursorText'), bg: h('ac1') }));
  ln(toml('ui.cursor.match',           { fg: h('ac1'), underline: { style: 'line' } }));

  // Selection & Highlights
  ln(toml('ui.selection',              { bg: h('selectionBg') }));
  ln(toml('ui.selection.primary',      { bg: h('selectionBg') }));
  ln(toml('ui.cursorline.primary',     { bg: h('lineHighlight') }));
  ln(toml('ui.highlight',              { bg: h('findMatch') }));

  // Line Numbers
  ln(toml('ui.linenr',                 { fg: h('comment') }));
  ln(toml('ui.linenr.selected',        { fg: h('ac1') }));

  // Virtual elements
  ln(toml('ui.virtual.ruler',          { bg: h('lineHighlight') }));
  ln(toml('ui.virtual.whitespace',     { fg: h('comment') }));
  ln(toml('ui.virtual.indent-guide',   { fg: h('comment') }));
  ln(toml('ui.virtual.indent-guide.active', { fg: h('ac2') }));
  ln(toml('ui.virtual.inlay-hint',     { fg: h('comment') }));
  ln(toml('ui.virtual.wrap',           { fg: h('comment') }));

  // Status line
  ln(toml('ui.statusline',             { fg: h('ac2Fg'), bg: h('ac2') }));
  ln(toml('ui.statusline.inactive',    { fg: h('comment'), bg: h('bg2') }));
  ln(toml('ui.statusline.normal',      { fg: h('ac1Fg'), bg: h('ac1') }));
  ln(toml('ui.statusline.insert',      { fg: h('ac2Fg'), bg: h('ac2') }));
  ln(toml('ui.statusline.select',      { fg: h('successFg'), bg: h('success') }));
  ln(toml('ui.statusline.separator',   { fg: h('border') }));

  // Panels & Menus
  ln(toml('ui.popup',                  { fg: h('fg1'), bg: h('bg2') }));
  ln(toml('ui.popup.info',             { fg: h('fg1'), bg: h('bg3') }));
  ln(toml('ui.window',                 { fg: h('border') }));
  ln(toml('ui.help',                   { fg: h('fg1'), bg: h('bg2') }));
  ln(toml('ui.menu',                   { fg: h('fg2'), bg: h('bg3') }));
  ln(toml('ui.menu.selected',          { fg: h('ac2Fg'), bg: h('ac2') }));
  ln(toml('ui.menu.scroll',            { fg: h('comment') }));

  // Gutter
  ln(toml('ui.gutter',                 { bg: h('bg1') }));
  ln(toml('ui.gutter.selected',        { bg: h('bg2') }));

  // Bufferline (tab bar)
  ln(toml('ui.bufferline',             { fg: h('comment'), bg: h('bg2') }));
  ln(toml('ui.bufferline.active',      { fg: h('fg1'), bg: h('bg1'), modifiers: ['bold'] }));
  ln(toml('ui.bufferline.background',  { bg: h('bg2') }));

  // ── Diagnostics ────────────────────────────────────────────────────────────

  ln('', '# ── Diagnostics ─────────────────────────────────────────────────────────────');
  ln(toml('diagnostic.hint',           { underline: { color: h('success'), style: 'curl' } }));
  ln(toml('diagnostic.info',           { underline: { color: h('info'), style: 'curl' } }));
  ln(toml('diagnostic.warning',        { underline: { color: h('warning'), style: 'curl' } }));
  ln(toml('diagnostic.error',          { underline: { color: h('error'), style: 'curl' } }));
  ln(toml('diagnostic.unnecessary',    { modifiers: ['dim'] }));
  ln(toml('diagnostic.deprecated',     { modifiers: ['crossed_out'] }));

  // ── Diff ───────────────────────────────────────────────────────────────────

  ln('', '# ── Diff ────────────────────────────────────────────────────────────────────');
  ln(toml('diff.plus',   { fg: h('success') }));
  ln(toml('diff.minus',  { fg: h('error') }));
  ln(toml('diff.delta',  { fg: h('info') }));

  // ── Markup ─────────────────────────────────────────────────────────────────

  ln('', '# ── Markup ──────────────────────────────────────────────────────────────────');
  ln(toml('markup.heading',    { fg: h('fg1'), modifiers: ['bold'] }));
  ln(toml('markup.heading.1',  { fg: h('ac1'), modifiers: ['bold'] }));
  ln(toml('markup.heading.2',  { fg: h('ac2'), modifiers: ['bold'] }));
  ln(toml('markup.heading.3',  { fg: h('info'), modifiers: ['bold'] }));
  ln(toml('markup.bold',       { modifiers: ['bold'] }));
  ln(toml('markup.italic',     { modifiers: ['italic'] }));
  ln(toml('markup.link.url',   { fg: h('info'), underline: { style: 'line' } }));
  ln(toml('markup.link.text',  { fg: h('info') }));
  ln(toml('markup.raw',        { fg: h('fg2') }));
  ln(toml('markup.raw.block',  { fg: h('fg2') }));
  ln(toml('markup.raw.inline', { fg: h('fg2') }));
  ln(toml('markup.quote',      { fg: h('comment'), modifiers: ['italic'] }));
  ln(toml('markup.list',       { fg: h('ac1') }));
  ln(toml('markup.list.checked',   { fg: h('success') }));
  ln(toml('markup.list.unchecked', { fg: h('comment') }));

  // ── Syntax Scopes ──────────────────────────────────────────────────────────

  ln('', '# ── Syntax ──────────────────────────────────────────────────────────────────');
  // Comments
  ln(toml('comment',                   { fg: h('comment'), modifiers: ['italic'] }));
  ln(toml('comment.block',             { fg: h('comment'), modifiers: ['italic'] }));
  ln(toml('comment.block.documentation', { fg: h('comment'), modifiers: ['italic'] }));
  ln(toml('comment.line',              { fg: h('comment'), modifiers: ['italic'] }));

  // Keywords
  ln(toml('keyword',                   { fg: h('keyword') }));
  ln(toml('keyword.control',           { fg: h('controlFlow') }));
  ln(toml('keyword.control.conditional', { fg: h('controlFlow') }));
  ln(toml('keyword.control.repeat',    { fg: h('controlFlow') }));
  ln(toml('keyword.control.import',    { fg: h('controlImport') }));
  ln(toml('keyword.control.return',    { fg: h('controlFlow') }));
  ln(toml('keyword.control.exception', { fg: h('controlFlow') }));
  ln(toml('keyword.function',          { fg: h('keyword') }));
  ln(toml('keyword.operator',          { fg: h('operator') }));
  ln(toml('keyword.storage',           { fg: h('storage') }));
  ln(toml('keyword.storage.modifier',  { fg: h('modifier') }));
  ln(toml('keyword.storage.type',      { fg: h('storage') }));

  // Functions
  ln(toml('function',                  { fg: h('function') }));
  ln(toml('function.call',             { fg: h('functionCall') }));
  ln(toml('function.method',           { fg: h('method') }));
  ln(toml('function.method.call',      { fg: h('methodCall') }));
  ln(toml('function.builtin',          { fg: h('supportFunction') }));
  ln(toml('function.macro',            { fg: h('modifier') }));

  // Variables
  ln(toml('variable',                  { fg: h('variable') }));
  ln(toml('variable.builtin',          { fg: h('language') }));
  ln(toml('variable.parameter',        { fg: h('parameter') }));
  ln(toml('variable.other',            { fg: h('variable') }));
  ln(toml('variable.other.member',     { fg: h('variableProperty') }));

  // Types
  ln(toml('type',                      { fg: h('type') }));
  ln(toml('type.builtin',              { fg: h('type') }));
  ln(toml('type.enum',                 { fg: h('type') }));
  ln(toml('type.enum.variant',         { fg: h('variableProperty') }));

  // Constants
  ln(toml('constant',                  { fg: h('constant') }));
  ln(toml('constant.builtin',          { fg: h('language') }));
  ln(toml('constant.builtin.boolean',  { fg: h('language') }));
  ln(toml('constant.numeric',          { fg: h('constant') }));
  ln(toml('constant.character',        { fg: h('constant') }));
  ln(toml('constant.character.escape', { fg: h('language') }));

  // Strings
  ln(toml('string',                    { fg: h('fg1') }));
  ln(toml('string.special',            { fg: h('ac2') }));
  ln(toml('string.special.symbol',     { fg: h('ac1') }));
  ln(toml('string.regexp',             { fg: h('fg2') }));

  // Operators & Punctuation
  ln(toml('operator',                  { fg: h('operator') }));
  ln(toml('punctuation',               { fg: h('punctuation') }));
  ln(toml('punctuation.bracket',       { fg: h('punctuationBrace') }));
  ln(toml('punctuation.delimiter',     { fg: h('punctuationComma') }));
  ln(toml('punctuation.special',       { fg: h('punctuationQuote') }));

  // Tags & Attributes
  ln(toml('tag',                       { fg: h('tag') }));
  ln(toml('tag.builtin',               { fg: h('tag') }));
  ln(toml('attribute',                 { fg: h('attribute') }));

  // Other
  ln(toml('constructor',               { fg: h('function') }));
  ln(toml('namespace',                 { fg: h('namespace') }));
  ln(toml('label',                     { fg: h('class') }));
  ln(toml('special',                   { fg: h('ac2') }));

  ln('');
  return lines.join('\n');
}
