import type { ThemePalette, VimExporterOptions } from '../types.js';

// ── Lua Serialization ──────────────────────────────────────────────────────────

interface HlOpts {
  fg?: string;
  bg?: string;
  sp?: string;
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  undercurl?: boolean;
  strikethrough?: boolean;
}

function luaOpts(opts: HlOpts): string {
  const parts: string[] = [];
  if (opts.fg)            parts.push(`fg = '${opts.fg}'`);
  if (opts.bg)            parts.push(`bg = '${opts.bg}'`);
  if (opts.sp)            parts.push(`sp = '${opts.sp}'`);
  if (opts.bold)          parts.push('bold = true');
  if (opts.italic)        parts.push('italic = true');
  if (opts.underline)     parts.push('underline = true');
  if (opts.undercurl)     parts.push('undercurl = true');
  if (opts.strikethrough) parts.push('strikethrough = true');
  return `{ ${parts.join(', ')} }`;
}

// ── Main Exporter ──────────────────────────────────────────────────────────────

/**
 * Export a ThemePalette to Neovim Lua colorscheme format (.lua).
 *
 * Produces a complete Lua colorscheme file with:
 * - UI highlight groups via `vim.api.nvim_set_hl(0, ...)`
 * - Spell checking (undercurl with sp)
 * - Diff highlights
 * - Diagnostic groups
 * - Legacy Vim syntax groups
 * - TreeSitter `@capture` groups for modern syntax highlighting
 * - Terminal ANSI palette via `vim.g.terminal_color_0..15`
 *
 * Extends the Vim exporter with:
 * - TreeSitter groups (@keyword, @function, @variable, @type, etc.)
 * - Terminal colors (g:terminal_color_0 through g:terminal_color_15)
 *
 * All gui colors are solid 6-digit hex (#RRGGBB). Overlay effects use bg2/bg3.
 *
 * @param palette - Resolved ThemePalette from extract() using createNvimSpec()
 * @param options - Optional name, author, colorSchemeName
 * @returns Lua string ready to save as a `.lua` colorscheme file
 */
export function exportNvim(palette: ThemePalette, options?: VimExporterOptions): string {
  const name = options?.colorSchemeName ?? options?.name ?? palette.spec;

  // Strip alpha — Nvim gui colors use 6-digit hex
  const h = (role: string) => {
    const hex = palette.hex(role) || '#000000';
    return hex.length > 7 ? hex.slice(0, 7) : hex;
  };

  const lines: string[] = [];
  const ln = (...args: string[]) => lines.push(...args);
  const hl = (group: string, opts: HlOpts) => ln(`h(0, '${group}', ${luaOpts(opts)})`);

  // ── Header ─────────────────────────────────────────────────────────────────

  ln(
    `-- ${name}.lua — Sacred Geometry color theme for Neovim`,
    `-- Generated by @rlabs-inc/theme-generator`,
    ``,
    `vim.cmd('highlight clear')`,
    `if vim.fn.exists('syntax_on') then`,
    `  vim.cmd('syntax reset')`,
    `end`,
    ``,
    `vim.o.background = '${palette.mode}'`,
    `vim.g.colors_name = '${name}'`,
    ``,
    `local h = vim.api.nvim_set_hl`,
    ``,
  );

  // ── UI Groups ──────────────────────────────────────────────────────────────

  ln('-- ── UI ──────────────────────────────────────────────────────────────────────');
  hl('Normal',       { fg: h('fg1'), bg: h('bg1') });
  hl('NormalFloat',  { fg: h('fg1'), bg: h('bg2') });
  hl('FloatBorder',  { fg: h('border'), bg: h('bg2') });
  hl('FloatTitle',   { fg: h('fg1'), bg: h('bg2'), bold: true });
  hl('Cursor',       { fg: h('cursorText'), bg: h('cursor') });
  hl('lCursor',      { fg: h('cursorText'), bg: h('cursor') });
  hl('CursorIM',     { fg: h('cursorText'), bg: h('cursor') });
  hl('CursorLine',   { bg: h('bg2') });
  hl('CursorColumn', { bg: h('bg2') });
  hl('ColorColumn',  { bg: h('bg3') });
  hl('Visual',       { bg: h('bg3') });
  hl('VisualNOS',    { bg: h('bg3') });
  hl('Search',       { fg: h('ac2Fg'), bg: h('ac2') });
  hl('IncSearch',    { fg: h('ac1Fg'), bg: h('ac1') });
  hl('CurSearch',    { fg: h('ac1Fg'), bg: h('ac1') });
  hl('Substitute',   { fg: h('ac1Fg'), bg: h('ac1') });
  hl('LineNr',       { fg: h('comment') });
  hl('CursorLineNr', { fg: h('ac1'), bold: true });
  hl('SignColumn',   { fg: h('comment'), bg: h('bg1') });
  hl('FoldColumn',   { fg: h('comment'), bg: h('bg1') });
  hl('Folded',       { fg: h('comment'), bg: h('bg3') });
  hl('VertSplit',    { fg: h('border') });
  hl('WinSeparator', { fg: h('border') });
  hl('StatusLine',   { fg: h('ac2Fg'), bg: h('ac2') });
  hl('StatusLineNC', { fg: h('comment'), bg: h('bg2') });
  hl('TabLine',      { fg: h('comment'), bg: h('bg2') });
  hl('TabLineFill',  { bg: h('bg2') });
  hl('TabLineSel',   { fg: h('fg1'), bg: h('bg1'), bold: true });
  hl('Pmenu',        { fg: h('fg2'), bg: h('bg3') });
  hl('PmenuSel',     { fg: h('ac2Fg'), bg: h('ac2') });
  hl('PmenuSbar',    { bg: h('bg3') });
  hl('PmenuThumb',   { bg: h('ac2') });
  hl('WildMenu',     { fg: h('ac2Fg'), bg: h('ac2') });
  hl('Title',        { fg: h('fg1'), bold: true });
  hl('NonText',      { fg: h('comment') });
  hl('EndOfBuffer',  { fg: h('comment') });
  hl('SpecialKey',   { fg: h('comment') });
  hl('Conceal',      { fg: h('comment') });
  hl('MatchParen',   { fg: h('ac1'), bold: true, underline: true });
  hl('ErrorMsg',     { fg: h('errorFg'), bg: h('error') });
  hl('WarningMsg',   { fg: h('warning') });
  hl('MoreMsg',      { fg: h('success') });
  hl('Question',     { fg: h('info') });
  hl('Directory',    { fg: h('info') });
  hl('ModeMsg',      { fg: h('fg1'), bold: true });

  // ── Spell ──────────────────────────────────────────────────────────────────

  ln('', '-- ── Spell ───────────────────────────────────────────────────────────────────');
  hl('SpellBad',   { undercurl: true, sp: h('error') });
  hl('SpellCap',   { undercurl: true, sp: h('warning') });
  hl('SpellRare',  { undercurl: true, sp: h('info') });
  hl('SpellLocal', { undercurl: true, sp: h('success') });

  // ── Diff ───────────────────────────────────────────────────────────────────

  ln('', '-- ── Diff ────────────────────────────────────────────────────────────────────');
  hl('DiffAdd',    { fg: h('success'), bg: h('bg2') });
  hl('DiffChange', { fg: h('info'), bg: h('bg2') });
  hl('DiffDelete', { fg: h('error'), bg: h('bg2') });
  hl('DiffText',   { fg: h('ac1'), bg: h('bg3'), bold: true });

  // ── Diagnostics ────────────────────────────────────────────────────────────

  ln('', '-- ── Diagnostics ─────────────────────────────────────────────────────────────');
  hl('DiagnosticError',             { fg: h('error') });
  hl('DiagnosticWarn',              { fg: h('warning') });
  hl('DiagnosticInfo',              { fg: h('info') });
  hl('DiagnosticHint',              { fg: h('success') });
  hl('DiagnosticUnderlineError',    { undercurl: true, sp: h('error') });
  hl('DiagnosticUnderlineWarn',     { undercurl: true, sp: h('warning') });
  hl('DiagnosticUnderlineInfo',     { undercurl: true, sp: h('info') });
  hl('DiagnosticUnderlineHint',     { undercurl: true, sp: h('success') });
  hl('DiagnosticVirtualTextError',  { fg: h('error') });
  hl('DiagnosticVirtualTextWarn',   { fg: h('warning') });
  hl('DiagnosticVirtualTextInfo',   { fg: h('info') });
  hl('DiagnosticVirtualTextHint',   { fg: h('success') });
  hl('DiagnosticSignError',         { fg: h('error') });
  hl('DiagnosticSignWarn',          { fg: h('warning') });
  hl('DiagnosticSignInfo',          { fg: h('info') });
  hl('DiagnosticSignHint',          { fg: h('success') });

  // ── Legacy Syntax Groups ───────────────────────────────────────────────────

  ln('', '-- ── Syntax ──────────────────────────────────────────────────────────────────');
  hl('Comment',        { fg: h('comment'), italic: true });
  hl('Constant',       { fg: h('constant') });
  hl('String',         { fg: h('fg1') });
  hl('Character',      { fg: h('constant') });
  hl('Number',         { fg: h('constant') });
  hl('Boolean',        { fg: h('language') });
  hl('Float',          { fg: h('constant') });
  hl('Identifier',     { fg: h('variable') });
  hl('Function',       { fg: h('function') });
  hl('Statement',      { fg: h('keyword') });
  hl('Conditional',    { fg: h('controlFlow') });
  hl('Repeat',         { fg: h('controlFlow') });
  hl('Label',          { fg: h('class') });
  hl('Operator',       { fg: h('operator') });
  hl('Keyword',        { fg: h('keyword') });
  hl('Exception',      { fg: h('controlFlow') });
  hl('PreProc',        { fg: h('modifier') });
  hl('Include',        { fg: h('controlImport') });
  hl('Define',         { fg: h('modifier') });
  hl('Macro',          { fg: h('modifier') });
  hl('PreCondit',      { fg: h('modifier') });
  hl('Type',           { fg: h('type') });
  hl('StorageClass',   { fg: h('storage') });
  hl('Structure',      { fg: h('type') });
  hl('Typedef',        { fg: h('type') });
  hl('Special',        { fg: h('ac2') });
  hl('SpecialChar',    { fg: h('language') });
  hl('Tag',            { fg: h('tag') });
  hl('Delimiter',      { fg: h('punctuation') });
  hl('SpecialComment', { fg: h('comment'), bold: true });
  hl('Debug',          { fg: h('warning') });
  hl('Error',          { fg: h('error') });
  hl('Todo',           { fg: h('info'), bold: true });

  // ── TreeSitter Groups ──────────────────────────────────────────────────────

  ln('', '-- ── TreeSitter ──────────────────────────────────────────────────────────────');
  // Keywords
  hl('@keyword',              { fg: h('keyword') });
  hl('@keyword.function',     { fg: h('keyword') });
  hl('@keyword.return',       { fg: h('controlFlow') });
  hl('@keyword.operator',     { fg: h('operator') });
  hl('@keyword.conditional',  { fg: h('controlFlow') });
  hl('@keyword.repeat',       { fg: h('controlFlow') });
  hl('@keyword.import',       { fg: h('controlImport') });
  hl('@keyword.storage',      { fg: h('storage') });
  hl('@keyword.modifier',     { fg: h('modifier') });
  hl('@keyword.exception',    { fg: h('controlFlow') });
  // Functions
  hl('@function',             { fg: h('function') });
  hl('@function.call',        { fg: h('functionCall') });
  hl('@function.method',      { fg: h('method') });
  hl('@function.method.call', { fg: h('methodCall') });
  hl('@function.builtin',     { fg: h('supportFunction') });
  hl('@function.macro',       { fg: h('modifier') });
  // Variables
  hl('@variable',             { fg: h('variable') });
  hl('@variable.builtin',     { fg: h('language') });
  hl('@variable.parameter',   { fg: h('parameter') });
  hl('@variable.member',      { fg: h('variableProperty') });
  // Types
  hl('@type',                 { fg: h('type') });
  hl('@type.builtin',         { fg: h('type') });
  hl('@type.definition',      { fg: h('type') });
  hl('@type.qualifier',       { fg: h('modifier') });
  // Constants
  hl('@constant',             { fg: h('constant') });
  hl('@constant.builtin',     { fg: h('language') });
  // Strings
  hl('@string',               { fg: h('fg1') });
  hl('@string.escape',        { fg: h('language') });
  hl('@string.special',       { fg: h('ac2') });
  hl('@string.regex',         { fg: h('fg2') });
  // Comments
  hl('@comment',              { fg: h('comment'), italic: true });
  hl('@comment.documentation', { fg: h('comment'), italic: true });
  hl('@comment.todo',         { fg: h('info'), bold: true });
  hl('@comment.error',        { fg: h('error'), bold: true });
  hl('@comment.warning',      { fg: h('warning'), bold: true });
  hl('@comment.note',         { fg: h('success'), bold: true });
  // Operators & Punctuation
  hl('@operator',             { fg: h('operator') });
  hl('@punctuation',          { fg: h('punctuation') });
  hl('@punctuation.bracket',  { fg: h('punctuationBrace') });
  hl('@punctuation.delimiter', { fg: h('punctuationComma') });
  hl('@punctuation.special',  { fg: h('punctuationQuote') });
  // Tags & Attributes
  hl('@tag',                  { fg: h('tag') });
  hl('@tag.delimiter',        { fg: h('tagPunctuation') });
  hl('@tag.attribute',        { fg: h('attribute') });
  // Other
  hl('@attribute',            { fg: h('attribute') });
  hl('@constructor',          { fg: h('function') });
  hl('@namespace',            { fg: h('namespace') });
  hl('@module',               { fg: h('namespace') });
  hl('@number',               { fg: h('constant') });
  hl('@number.float',         { fg: h('constant') });
  hl('@boolean',              { fg: h('language') });
  hl('@property',             { fg: h('property') });
  hl('@label',                { fg: h('class') });
  // Markup
  hl('@markup.heading',       { fg: h('fg1'), bold: true });
  hl('@markup.bold',          { bold: true });
  hl('@markup.italic',        { italic: true });
  hl('@markup.link',          { fg: h('info') });
  hl('@markup.link.url',      { fg: h('info'), underline: true });
  hl('@markup.raw',           { fg: h('fg2') });
  hl('@markup.list',          { fg: h('ac1') });

  // ── Terminal Colors ────────────────────────────────────────────────────────

  ln('', '-- ── Terminal Colors ──────────────────────────────────────────────────────────');
  ln(`vim.g.terminal_color_0  = '${h('ansiBlack')}'`);
  ln(`vim.g.terminal_color_1  = '${h('ansiRed')}'`);
  ln(`vim.g.terminal_color_2  = '${h('ansiGreen')}'`);
  ln(`vim.g.terminal_color_3  = '${h('ansiYellow')}'`);
  ln(`vim.g.terminal_color_4  = '${h('ansiBlue')}'`);
  ln(`vim.g.terminal_color_5  = '${h('ansiMagenta')}'`);
  ln(`vim.g.terminal_color_6  = '${h('ansiCyan')}'`);
  ln(`vim.g.terminal_color_7  = '${h('ansiWhite')}'`);
  ln(`vim.g.terminal_color_8  = '${h('ansiBrightBlack')}'`);
  ln(`vim.g.terminal_color_9  = '${h('ansiBrightRed')}'`);
  ln(`vim.g.terminal_color_10 = '${h('ansiBrightGreen')}'`);
  ln(`vim.g.terminal_color_11 = '${h('ansiBrightYellow')}'`);
  ln(`vim.g.terminal_color_12 = '${h('ansiBrightBlue')}'`);
  ln(`vim.g.terminal_color_13 = '${h('ansiBrightMagenta')}'`);
  ln(`vim.g.terminal_color_14 = '${h('ansiBrightCyan')}'`);
  ln(`vim.g.terminal_color_15 = '${h('ansiBrightWhite')}'`);

  ln('');
  return lines.join('\n');
}
