import type { ThemePalette, VimExporterOptions } from '../types.js';

/**
 * Export a ThemePalette to Vim colorscheme format (.vim).
 *
 * Produces a complete VimScript colorscheme file with:
 * - UI highlight groups (Normal, Cursor, Visual, Search, StatusLine, etc.)
 * - Spell checking (undercurl with guisp)
 * - Diff highlights
 * - Diagnostic groups (DiagnosticError, DiagnosticUnderlineError, etc.)
 * - Legacy Vim syntax groups (Comment, Keyword, Function, Type, etc.)
 *
 * All colors are solid 6-digit hex (#RRGGBB) — Vim does not support alpha
 * in gui colors. Overlay effects (selection, cursorline, search) use bg2/bg3
 * for layered backgrounds instead of semi-transparent overlays.
 *
 * Note: Vim colorschemes do NOT control terminal ANSI palette. For Neovim
 * with `g:terminal_color_*` support, use exportNvim() instead.
 *
 * @param palette - Resolved ThemePalette from extract() using createVimSpec()
 * @param options - Optional name, author, colorSchemeName
 * @returns VimScript string ready to save as a `.vim` colorscheme file
 */
export function exportVim(palette: ThemePalette, options?: VimExporterOptions): string {
  const name = options?.colorSchemeName ?? options?.name ?? palette.spec;

  // Strip alpha — Vim only supports 6-digit hex in gui colors
  const h = (role: string) => {
    const hex = palette.hex(role) || '#000000';
    return hex.length > 7 ? hex.slice(0, 7) : hex;
  };

  const lines: string[] = [];
  const ln = (...args: string[]) => lines.push(...args);
  const hi = (group: string, attrs: string) => ln(`hi ${group} ${attrs}`);

  // ── Header ─────────────────────────────────────────────────────────────────

  ln(
    `" ${name}.vim — Sacred Geometry color theme for Vim`,
    `" Generated by @rlabs-inc/theme-generator`,
    ``,
    `set background=${palette.mode}`,
    `highlight clear`,
    `if exists('syntax_on')`,
    `  syntax reset`,
    `endif`,
    `let g:colors_name = '${name}'`,
    ``,
  );

  // ── UI Groups ──────────────────────────────────────────────────────────────

  ln('" ── UI ──────────────────────────────────────────────────────────────────────');
  hi('Normal',       `guifg=${h('fg1')} guibg=${h('bg1')}`);
  hi('NormalFloat',  `guifg=${h('fg1')} guibg=${h('bg2')}`);
  hi('FloatBorder',  `guifg=${h('border')} guibg=${h('bg2')}`);
  hi('FloatTitle',   `guifg=${h('fg1')} guibg=${h('bg2')} gui=bold`);
  hi('Cursor',       `guifg=${h('cursorText')} guibg=${h('cursor')}`);
  hi('lCursor',      `guifg=${h('cursorText')} guibg=${h('cursor')}`);
  hi('CursorIM',     `guifg=${h('cursorText')} guibg=${h('cursor')}`);
  hi('CursorLine',   `guibg=${h('bg2')} gui=NONE`);
  hi('CursorColumn', `guibg=${h('bg2')}`);
  hi('ColorColumn',  `guibg=${h('bg3')}`);
  hi('Visual',       `guifg=NONE guibg=${h('bg3')}`);
  hi('VisualNOS',    `guifg=NONE guibg=${h('bg3')}`);
  hi('Search',       `guifg=${h('ac2Fg')} guibg=${h('ac2')}`);
  hi('IncSearch',    `guifg=${h('ac1Fg')} guibg=${h('ac1')}`);
  hi('CurSearch',    `guifg=${h('ac1Fg')} guibg=${h('ac1')}`);
  hi('Substitute',   `guifg=${h('ac1Fg')} guibg=${h('ac1')}`);
  hi('LineNr',       `guifg=${h('comment')}`);
  hi('CursorLineNr', `guifg=${h('ac1')} gui=bold`);
  hi('SignColumn',   `guifg=${h('comment')} guibg=${h('bg1')}`);
  hi('FoldColumn',   `guifg=${h('comment')} guibg=${h('bg1')}`);
  hi('Folded',       `guifg=${h('comment')} guibg=${h('bg3')}`);
  hi('VertSplit',    `guifg=${h('border')} guibg=NONE`);
  hi('WinSeparator', `guifg=${h('border')} guibg=NONE`);
  hi('StatusLine',   `guifg=${h('ac2Fg')} guibg=${h('ac2')}`);
  hi('StatusLineNC', `guifg=${h('comment')} guibg=${h('bg2')}`);
  hi('TabLine',      `guifg=${h('comment')} guibg=${h('bg2')}`);
  hi('TabLineFill',  `guibg=${h('bg2')}`);
  hi('TabLineSel',   `guifg=${h('fg1')} guibg=${h('bg1')} gui=bold`);
  hi('Pmenu',        `guifg=${h('fg2')} guibg=${h('bg3')}`);
  hi('PmenuSel',     `guifg=${h('ac2Fg')} guibg=${h('ac2')}`);
  hi('PmenuSbar',    `guibg=${h('bg3')}`);
  hi('PmenuThumb',   `guibg=${h('ac2')}`);
  hi('WildMenu',     `guifg=${h('ac2Fg')} guibg=${h('ac2')}`);
  hi('Title',        `guifg=${h('fg1')} gui=bold`);
  hi('NonText',      `guifg=${h('comment')}`);
  hi('EndOfBuffer',  `guifg=${h('comment')}`);
  hi('SpecialKey',   `guifg=${h('comment')}`);
  hi('Conceal',      `guifg=${h('comment')}`);
  hi('MatchParen',   `guifg=${h('ac1')} gui=bold,underline`);
  hi('ErrorMsg',     `guifg=${h('errorFg')} guibg=${h('error')}`);
  hi('WarningMsg',   `guifg=${h('warning')}`);
  hi('MoreMsg',      `guifg=${h('success')}`);
  hi('Question',     `guifg=${h('info')}`);
  hi('Directory',    `guifg=${h('info')}`);
  hi('ModeMsg',      `guifg=${h('fg1')} gui=bold`);

  // ── Spell ──────────────────────────────────────────────────────────────────

  ln('', '" ── Spell ───────────────────────────────────────────────────────────────────');
  hi('SpellBad',    `gui=undercurl guisp=${h('error')}`);
  hi('SpellCap',    `gui=undercurl guisp=${h('warning')}`);
  hi('SpellRare',   `gui=undercurl guisp=${h('info')}`);
  hi('SpellLocal',  `gui=undercurl guisp=${h('success')}`);

  // ── Diff ───────────────────────────────────────────────────────────────────

  ln('', '" ── Diff ────────────────────────────────────────────────────────────────────');
  hi('DiffAdd',    `guifg=${h('success')} guibg=${h('bg2')}`);
  hi('DiffChange', `guifg=${h('info')} guibg=${h('bg2')}`);
  hi('DiffDelete', `guifg=${h('error')} guibg=${h('bg2')}`);
  hi('DiffText',   `guifg=${h('ac1')} guibg=${h('bg3')} gui=bold`);

  // ── Diagnostics ────────────────────────────────────────────────────────────

  ln('', '" ── Diagnostics ─────────────────────────────────────────────────────────────');
  hi('DiagnosticError',             `guifg=${h('error')}`);
  hi('DiagnosticWarn',              `guifg=${h('warning')}`);
  hi('DiagnosticInfo',              `guifg=${h('info')}`);
  hi('DiagnosticHint',              `guifg=${h('success')}`);
  hi('DiagnosticUnderlineError',    `gui=undercurl guisp=${h('error')}`);
  hi('DiagnosticUnderlineWarn',     `gui=undercurl guisp=${h('warning')}`);
  hi('DiagnosticUnderlineInfo',     `gui=undercurl guisp=${h('info')}`);
  hi('DiagnosticUnderlineHint',     `gui=undercurl guisp=${h('success')}`);
  hi('DiagnosticVirtualTextError',  `guifg=${h('error')}`);
  hi('DiagnosticVirtualTextWarn',   `guifg=${h('warning')}`);
  hi('DiagnosticVirtualTextInfo',   `guifg=${h('info')}`);
  hi('DiagnosticVirtualTextHint',   `guifg=${h('success')}`);
  hi('DiagnosticSignError',         `guifg=${h('error')}`);
  hi('DiagnosticSignWarn',          `guifg=${h('warning')}`);
  hi('DiagnosticSignInfo',          `guifg=${h('info')}`);
  hi('DiagnosticSignHint',          `guifg=${h('success')}`);

  // ── Syntax Groups ─────────────────────────────────────────────────────────

  ln('', '" ── Syntax ──────────────────────────────────────────────────────────────────');
  hi('Comment',        `guifg=${h('comment')} gui=italic`);
  hi('Constant',       `guifg=${h('constant')}`);
  hi('String',         `guifg=${h('fg1')}`);
  hi('Character',      `guifg=${h('constant')}`);
  hi('Number',         `guifg=${h('constant')}`);
  hi('Boolean',        `guifg=${h('language')}`);
  hi('Float',          `guifg=${h('constant')}`);
  hi('Identifier',     `guifg=${h('variable')}`);
  hi('Function',       `guifg=${h('function')}`);
  hi('Statement',      `guifg=${h('keyword')} gui=NONE`);
  hi('Conditional',    `guifg=${h('controlFlow')}`);
  hi('Repeat',         `guifg=${h('controlFlow')}`);
  hi('Label',          `guifg=${h('class')}`);
  hi('Operator',       `guifg=${h('operator')}`);
  hi('Keyword',        `guifg=${h('keyword')}`);
  hi('Exception',      `guifg=${h('controlFlow')}`);
  hi('PreProc',        `guifg=${h('modifier')}`);
  hi('Include',        `guifg=${h('controlImport')}`);
  hi('Define',         `guifg=${h('modifier')}`);
  hi('Macro',          `guifg=${h('modifier')}`);
  hi('PreCondit',      `guifg=${h('modifier')}`);
  hi('Type',           `guifg=${h('type')} gui=NONE`);
  hi('StorageClass',   `guifg=${h('storage')}`);
  hi('Structure',      `guifg=${h('type')}`);
  hi('Typedef',        `guifg=${h('type')}`);
  hi('Special',        `guifg=${h('ac2')}`);
  hi('SpecialChar',    `guifg=${h('language')}`);
  hi('Tag',            `guifg=${h('tag')}`);
  hi('Delimiter',      `guifg=${h('punctuation')}`);
  hi('SpecialComment', `guifg=${h('comment')} gui=bold`);
  hi('Debug',          `guifg=${h('warning')}`);
  hi('Error',          `guifg=${h('error')}`);
  hi('Todo',           `guifg=${h('info')} gui=bold`);

  ln('');
  return lines.join('\n');
}
